import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TanstackProvider from '@/providers/TanstackProvider'
import AuthProvider from '@/providers/AuthProvider'
import Navbar from './components/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<TanstackProvider>
					<AuthProvider>
						<Navbar />
						{children}
					</AuthProvider>
				</TanstackProvider>
			</body>
		</html>
	)
}
